name: spawner-cdk-go

description: 'xxx'

author: "xxx"

branding:
  icon: "alert-triangle"
  color: "blue"

inputs:
  go-version:
    description: |
      xxx
    required: true
    default: 1.18

  cache-key:
    description: |
      xxx
    required: false

  stack:
    description: |
      xxx
    required: true

  version:
    description: |
      xxx
    required: true

  aws-access-key:
    description: |
      xxx
    required: true

  aws-secret-key:
    description: |
      xxx
    required: true

  aws-region:
    description: |
      xxx
    required: true

  issue-to-comment:
    description: |
      xxx
    required: false
    default: ''

  issue-to-create:
    description: |
      xxx
    required: false
    default: ''
  
runs:
  using: "composite"
  steps:
    - uses: peter-evans/create-issue-from-file@v4
      id: issue
      if: ${{ inputs.issue-to-create != '' }} 
      with:
        title: Spawns `${{ inputs.version }}` of `${{ inputs.stack }}` to the cloud 
        content-filepath: ${{ inputs.issue-to-create }}

    - uses: peter-evans/create-or-update-comment@v2
      if: ${{ inputs.issue-to-create != '' && inputs.issue-to-comment != '' }}
      issue-number: ${{ steps.issue.outputs.issue-number }}
          body: |
            TODO #${{ inputs.issue-to-comment }}

    - uses: peter-evans/create-or-update-comment@v2
      if: ${{ inputs.issue-to-create != '' && inputs.issue-to-comment != '' }}
      issue-number: ${{ inputs.issue-to-comment }}
          body: |
            TODO #${{ steps.issue.outputs.issue-number }}

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - uses: actions/cache@v3
      if: ${{ inputs.cache-key != '' }}
      with:
        path: ./cdk.out
        key: ${{ inputs.cache-key }}-${{ inputs.stack }}-${{ runner.os }}-cdk-${{ hashFiles('**/manifest.json') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ inputs.stack }}-${{ runner.os }}-cdk-

    - name: setup-cdk
      shell: bash
      run: |
        npm install -g aws-cdk

    - name: aws access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: cdk deploy
      shell: bash
      run: |
        cdk deploy ${{ inputs.stack }}-${{ inputs.version }} \
          -c vsn=${{ inputs.version }} \
          --outputs-file $GITHUB_WORKSPACE/stack.json
      env:
        GOPATH: /home/runner/go
        GOCACHE: /home/runner/.cache/go-build
        GOMODCACHE: /home/runner/go/pkg/mod

    ##
    ## discover url of deployed api and runs api testing   
    - id: discover
      shell: bash
      run: |
        echo ::set-output name=target::$(jq -r '.["${{ inputs.stack }}-${{ inputs.version }}"] | to_entries | .[] | select(.key|test("GatewayEndpoint.*")) | .value ' < $GITHUB_WORKSPACE/stack.json)

    - uses: peter-evans/create-or-update-comment@v2
      if: ${{ inputs.issue-to-comment != '' }} 
      with:
        issue-number: ${{ inputs.issue-to-comment }}
        body: |
          Sandbox for **${{ inputs.stack }}** is deployed to cloud environment:
          - **url**: ${{ steps.discover.outputs.target }}
        reactions: rocket

    - uses: peter-evans/close-issue@v2
      if: ${{ inputs.issue-to-create != '' }} 
      with:
        issue-number: ${{ steps.issue.outputs.issue-number }}
        comment: |
          Version `${{ inputs.version }}` of **${{ inputs.stack }}** is deployed to cloud environment:
          - **url**: ${{ steps.discover.outputs.target }}

