name: spawner-cdk-go

description: 'xxx'

author: "xxx"

branding:
  icon: "alert-triangle"
  color: "blue"

inputs:
  go-version:
    description: |
      xxx
    required: true
    default: 1.18

  stack:
    description: |
      xxx
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - shell: bash
      run: |
        echo "==> ${{ inputs.stack }}"
